# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10wdW4eR7Or3CGVMdOTDDnXShRSojfICD
"""

def Add(a: str, b: str) -> str:
    return a + b
def Mult(s: str, n: int) -> str:
    if not isinstance(n, int) or n < 0:
        raise ValueError("n должно быть целым неотрицательным числом")
    return s * n
def Reverse(s: str) -> str:
    return s[::-1]
def CountVowels(s: str) -> int:
    vowels = "аеёиоуыэюяАЕЁИОУЫЭЮЯ"
    return sum(1 for char in s if char in vowels)

result = Add("Hello, ", "world!")
print(result) 
print(Mult("abc", 3))  
print(Mult("!", 5))
print(Mult("mashatanya", 10))
print(Mult("test", 0)) 
print(Reverse("hello"))
result = Add("Hello, ", "world!")
print(result) 
print(CountVowels("программирование"))
